# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:

  orderer.example.com:
    volumes:
      - ./ledgers/orderer.example.com:/var/hyperledger/production/orderer

  peer0.org1.example.com:
    volumes:
      - ./ledgers/peer0.org1.example.com:/var/hyperledger/production

  peer1.org1.example.com:
    volumes:
      - ./ledgers/peer1.org1.example.com:/var/hyperledger/production

  peer0.org2.example.com:
    volumes:
      - ./ledgers/peer0.org2.example.com:/var/hyperledger/production

  peer1.org2.example.com:
    volumes:
      - ./ledgers/peer1.org2.example.com:/var/hyperledger/production
