name: Test Network Off Chain
run-name: ${{ github.actor }} is running the test-network off chain data tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  off-chain:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        chaincode-language:
          - go
          - javascript
          - typescript
          - java

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install fabric CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/hyperledger/fabric/main/scripts/install-fabric.sh | bash -s -- binary
          echo ${PWD}/bin >> $GITHUB_PATH

      - name: Pull Fabric Docker Images
        run: curl -sSL https://raw.githubusercontent.com/hyperledger/fabric/main/scripts/install-fabric.sh | bash -s -- docker

      - name: Install retry CLI
        run: curl -sSL https://raw.githubusercontent.com/kadwanev/retry/master/retry -o ./bin/retry && chmod +x ./bin/retry

      - name: Run Test Network Off Chain
        working-directory: test-network
        env:
          CHAINCODE_LANGUAGE: ${{ matrix.chaincode-language }}
        run: ../ci/scripts/run-test-network-off-chain.sh

